global:
  domain: argocd.127.0.0.1.nip.io
configs:
  secret:
    argocdServerAdminPassword: "$2y$10$20DSiCIztVd7txaQdtQj7OOBqEFWtWJUYWaFWdBroSiiXn.CxuPXK"
    argocdServerAdminPasswordMtime: "2024-12-10T17:00:00Z"
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 60s
  params:
    "server.insecure": true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
  extraArgs:
    - --insecure
